<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->translate('LYNX Technik Controllers') ?></h1>
</div>

<div class="content" data-base-target="_next">
<?= $this->qlink($this->translate('Add new controller'), 'lynxtechnik/add/controller') ?>
<?php if (empty($this->list)): ?>
<br /><?= $this->translate('No controller found') ?>
</div>
<?php return; endif ?>

<table class="action">
<?php foreach ($this->list as $row): ?>
<tr>
  <td><?= $this->qlink(
  long2ip($row->ip_address),
  'lynxtechnik/modify/controller',
  array(
      'id' => $row->id
  )) ?></td>
  <td><?= date('Y-m-d H:i:s', $row->last_discovery) ?>
</tr>
<?php endforeach ?>
</table>
</div>
