<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->translate('Icinga Templates') ?></h1>
<?= $this->qlink(
    $this->translate('Add'),
    'lynxtechnik/add/template',
    null,
    array(
        'class' => 'action icon-plus',
        'title' => $this->translate('Add new Icinga Template'),
    )
) ?>
</div>

<div class="content" data-base-target="_next">
<?php if (empty($this->list)): ?>
<br /><?= $this->translate('No template found') ?>
</div>
<?php return; endif ?>

<table class="action">
<?php foreach ($this->list as $row): ?>
<tr>
  <td><?= $this->qlink(
  sprintf('%s (%s: %s)', $row->title, $row->type, $row->name),
  'lynxtechnik/modify/template',
  array(
      'id' => $row->id
  )) ?></td>
</tr>
<?php endforeach ?>
</table>
</div>
